# Generated by Django 5.0.6 on 2024-07-09 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="unique_post_comment",
        ),
    ]
