# Generated by Django 5.0.6 on 2024-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_remove_comment_unique_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrabpost",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="scrabpost",
            name="post_picture",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="scrabpost",
            name="title",
            field=models.CharField(default=" ", max_length=255),
        ),
    ]
