# Generated by Django 5.0.6 on 2024-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "kakao_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("nickname", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "thumbnail_image",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
